### PR TITLE
Add install section to meson build

### PR DESCRIPTION
**Pull request by Scrumplex**
This should make it easier to package for distributions. :frog:

### CODE REVIEW

**Comment by Scrumplex** [comment]
Technically this should require `vulkan-headers` as a dependency, but it seems like there is no pkgconfig file for that :(

**Comment by misyltoad** [comment]
Thanks, I am not sure we want to do this yet as I am not making any guarantees on ABI stability at the moment.
It would be better for projects using it to pull it in as a submodule and use the header directly for now.

**Comment by Scrumplex** [comment]
Hmm, good point. My main idea was just to package this on the AUR for the three people who would want to install it like that instead :eyes:.
If you don't want this for now, feel free to close the PR :D



:frog:

**Comment by jhvst** [comment]
I second this PR. vkroots is now a dependency of [gamescope](https://github.com/Plagman/gamescope/tree/master). I tried to upgrade gamescope today on NixOS but I need to build this package as a part of that upgrade process. It'd be better for reproducibility if vkroots can be built standalone hence the version pinned with a package manager as well.

**Comment by misyltoad** [comment]
My problem here is, I do not wish to commit to any ABI stability at this point of development.

I will merge it with the health warning, that I make no commitment to that at this point in time.

**Pull request merged**
