### PR TITLE
fix compile error w.r.t. gamescope/layer-maintenance1-framelatencyaware

### PR DESCRIPTION
**Pull request by sharkautarch**

### CODE REVIEW

**Comment by misyltoad** [comment]
Hmm, I don't have any compile errors. Can you give me more info as to what you see?

**Comment by sharkautarch** [comment]
> Hmm, I don't have any compile errors. Can you give me more info as to what you see?

when compiling gamescope/layer-maintenance1-framelatencyaware (with gcc), I got:
```
./subprojects/vkroots/vkroots.h:16639:11: error: no match for call to ‘(vkroots::helpers::array<VkPresentModeKHR*, const std::array<VkPresentModeKHR, 1> >(const std::array<VkPresentModeKHR, 1>&, uint32_t*, VkPresentModeKHR**)::<lambda(VkPresentModeKHR*&, VkPresentModeKHR* const&)>) (VkPresentModeKHR*&, const std::array<VkPresentModeKHR, 1>::value_type&)’
16639 |       func(pOut[i], arr[i]);

../subprojects/vkroots/vkroots.h:16639:11: note: candidate: ‘void (*)(VkPresentModeKHR*&, VkPresentModeKHR* const&)’ (conversion)
../subprojects/vkroots/vkroots.h:16639:11: note:   candidate expects 3 arguments, 3 provided
../subprojects/vkroots/vkroots.h:16649:37: note: candidate: ‘vkroots::helpers::array<VkPresentModeKHR*, const std::array<VkPresentModeKHR, 1> >(const std::array<VkPresentModeKHR, 1>&, uint32_t*, VkPresentModeKHR**)::<lambda(VkPresentModeKHR*&, VkPresentModeKHR* const&)>’
16649 |     return array(arr, pCount, pOut, [](T& x, const T& y) { x = y; });
      |                                     ^
../subprojects/vkroots/vkroots.h:16649:37: note:   no known conversion for argument 2 from ‘const std::array<VkPresentModeKHR, 1>::value_type’ {aka ‘const VkPresentModeKHR’} to ‘VkPresentModeKHR* const&’
```

I believe it's the same error from the CI build check:
https://github.com/ValveSoftware/gamescope/pull/1129/checks

Also I made sure to remove the dir `subprojects/vkroots` and then run 
`git submodule init --update` (to make sure vkroots was the same as w/ upstream vkroots) 
and then run
`meson setup build  --reconfigure --wipe --buildtype=debugoptimized -Db_sanitize=none -Db_ndebug=false -Dc_args="" -Dc_link_args="" -Dcpp_args="" -Dcpp_link_args=""` before building

**Comment by misyltoad** [comment]
This is because there is a typo in what I committed =) 

It should be `vkroots::helpers::array(s_FifoModes, &pPresentModeCompat->presentModeCount, pPresentModeCompat->pPresentModes);`

**Comment by sharkautarch** [comment]
> This is because there is a typo in what I committed =)
> 
> It should be `vkroots::helpers::array(s_FifoModes, &pPresentModeCompat->presentModeCount, pPresentModeCompat->pPresentModes);`


Ahhh that makes sense lol

**Pull request closed without merging**
